spring.application.name=motor-decisiones

# Credenciales de la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Proactividad100%

# Configuracion de Hibernate (El trabajador de JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACION DE SEGURIDAD (JWT)
# ==========================================
# Esta clave tiene 64 caracteres (512 bits), garantizando inmunidad a ataques de fuerza bruta
jwt.secret=4z7C9bK2wM5v8yB1eR4t7w!z%C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s
# Tiempo de validez del pasaporte (ej. 86400000 milisegundos = 24 horas)
jwt.expiration=86400000

# 1-Configuracion de la base de datos
# 2-colocacion de su contrasena e instalacion
# 3-setup exitoso SpringBoot 3 con Java 21 y conexion a PostgreSQL 16

# ==========================================
# CONFIGURACION DE APACHE KAFKA (PRODUCTOR)
# ==========================================
# Direccion de tu contenedor Docker de Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Como convertir las llaves y los mensajes a Texto (String) antes de enviarlos
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ==========================================
# CONFIGURACION DE APACHE KAFKA (CONSUMIDOR)
# ==========================================
# El "grupo" al que pertenece tu aplicacion (util si tienes varios servidores)
spring.kafka.consumer.group-id=tesis-group
# Como convertir los bytes que llegan de vuelta a Texto (String)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Si es la primera vez que se conecta, que lea desde el principio de los tiempos
spring.kafka.consumer.auto-offset-reset=earliest