spring.application.name=motor-decisiones

# ==========================================
# CREDENCIALES DE LA BASE DE DATOS (NUBE)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate creara/actualizara las tablas automaticamente
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# ==========================================
# CONFIGURACION DE SEGURIDAD (JWT)
# ==========================================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000